### ISSUE TITLE
Expected public key to be an Uint8Array with length [33, 65]

### ISSUE THREAD

**Issue by tecoLai** [blockchain-certificates/blockcerts-verifier#1411]
Hi guys,

I am trying to validate a valid json Blockcerts credential V2 and Im getting the following error in the Identity verification step:

Expected public key to be an Uint8Array with length [33, 65] 

<img width="390" alt="screenshot1" src="https://github.com/blockchain-certificates/blockcerts-verifier/assets/38200941/e17367e6-eff9-4c83-b456-f19ffdadd0ad">

Here is my valid json:
```
{
	"@context": ["https://www.w3.org/2018/credentials/v1", "https://w3id.org/blockcerts/v3"],
	"id": "urn:uuid:bbba8553-8ec1-445f-82c9-a57251dd731c",
	"type": ["VerifiableCredential", "BlockcertsCredential"],
	"issuer": "did:web:d17ab87jdkvb30.cloudfront.net",
	"issuanceDate": "2023-05-18T00:00:00Z",
	"credentialSubject": {"id": "did:example:ebfeb1f712ebc6f1c276e12ec21", "name": "LAI"},
	"proof": {
		"type": "MerkleProof2019",
		"created": "2023-05-18T07:38:21.617957",
		"proofValue": "znKD4YGVqA8texttcfpkbF2mPUYAguT8rCYUw4i2ocLkDtYC326bidW8hFzjneDy2TLgD5gu4fpeBsZH4hgDqvkpKT7SQSuXpLWipJ3Kia7Y8T3c8mDcs11Y6Ay5FYLrDXGANx11u22LRwckBxUxuatR3GqVJ795eTcPZDzg9YJdLxzA6ydMJdnY2PzSfHg61U3ksvNo9cvTKWbJM34i8cSvQzgiAkmQagNcNzHRPBNU29tHckJs5K4nAit6EzCAAQyRUD73PgJw76ipFRvkziaWLrNeZT8av5aSUCKrEZLNXkyYMwKZ5trCtns",
		"proofPurpose": "assertionMethod",
		"verificationMethod": "did:web:d17ab87jdkvb30.cloudfront.net#key-1"
	}
}
```

I can not get reason that why this error message happened.

It will save me day if somebody know that how to fix it.

Thanks

**Comment by lemoustachiste** [comment]
Hi @tecoLai,

so I've never seen this error before. What I believe may be up is that the public key stored in the DID document is malformed, or at least not compatible with the current key decoding support in the verifier library.

Here is the DID document bound to it:

```
{
  "@context": [
    "https://www.w3.org/ns/did/v1"
  ],
  "id": "did:web:d17ab87jdkvb30.cloudfront.net",
  "service": [
    {
      "id": "#issuer-profile",
      "type": "IssuerProfile",
      "serviceEndpoint": "https://d17ab87jdkvb30.cloudfront.net/forPublic/profile.json"
    }
  ],
  "verificationMethod": [
    {
      "id": "#key-1",
      "controller": "did:web:d17ab87jdkvb30.cloudfront.net",
      "type": "EcdsaSecp256k1VerificationKey2019",
      "publicKeyJwk": {
        "kty": "EC",
        "crv": "K-256",
        "x": "lmbEwMqXvXotyOLh70yc",
        "y": "R3xgpNtllFwiHNaUljgl"
      }
    }
  ]
}
```

If you look at this example profile: https://www.blockcerts.org/samples/3.0/issuer-blockcerts.json, the secp256k1 are defined somewhat differently. 

I'm not saying your implementation is wrong, I believe more likely that your case is not covered.

May I ask how did you generate the key there (which library and version did you use?), and how then did you derive the issuing address?

**Comment by tecoLai** [comment]
@lemoustachiste 

Thank you for your response.

> May I ask how did you generate the key there (which library and version did you use?), and how then did you derive the issuing address?

I generate my public key through Ethereum wallet secret key.

I use this script the help me to generate the public key.

```
# coverts.js
const fs = require('fs');
const keyto = require("@trust/keyto");

if (require.main === module) {
  main();
}

function main() {
  const file = process.argv[2];
  const blk = fs.readFileSync(file, 'utf-8');
  const key = keyto.from(blk, "blk");
  const jwk = key.toJwk("public");

  console.log(JSON.stringify(jwk, null, 2));
} 
```

And I store my secret key in the key_file.txt, the content is like this.

```
# this is example
1234567890123456789012345678901234567890123456789012345678901234
```

And then run the command as below.

```
node convert.js key_file.txt
```

>If you look at this example profile: https://www.blockcerts.org/samples/3.0/issuer-blockcerts.json, the secp256k1 are defined somewhat differently.

yes, I also found the the length of x and y in my case that is short then your example.
But I am not sure which part was wrong.

**Comment by tecoLai** [comment]
@lemoustachiste 

Hi, I just fix the issue.

I am not sure but the issue gone after I reinstall library.

Thank you

**Comment by lemoustachiste** [comment]
Great!
