### ISSUE TITLE
Error Failed to replace env in config: ${NPM_TOKEN} 

### ISSUE THREAD

**Issue by Skyquek** [blockchain-certificates/blockcerts-verifier#145]
Failed to replace env in config: ${NPM_TOKEN}  occur when run 
$ npm i @blockcerts/blockcerts-verifier

**Comment by lemoustachiste** [comment]
You probably need to expose your NPM token in your bash window.
You can either do it manually `export NPM_TOKEN=your-npm-token`, or add the same instruction at the end of your .bashrc file if you want this to be set automatically.

**Comment by AnthonyRonning** [comment]
@lemoustachiste could we add that to the README instructions?

**Comment by lemoustachiste** [comment]
@Skyquek did this fix your problem?

**Comment by Skyquek** [comment]
Nope, I am not sure where to get my npm token. I open up a new project directory and install via node jsseems to help fix the problem. So at the end, I didn't try the demo.

**Comment by lemoustachiste** [comment]
NPM Tokens are available in your npm account.
https://docs.npmjs.com/creating-and-viewing-authentication-tokens
