### ISSUE TITLE
Unsigned certificates don't fail correctly

### ISSUE THREAD

**Issue by AnthonyRonning** [blockchain-certificates/blockcerts-verifier#16]
When uploading a valid unsigned certificate (I used [this one](https://raw.githubusercontent.com/blockchain-certificates/cert-issuer/master/examples/data-testnet/unsigned_certificates/3bc1a96a-3501-46ed-8f75-49612bbac257.json)) to blockcerts.org, the following is the reaction: 

<img width="832" alt="screen shot 2018-11-12 at 9 05 05 am" src="https://user-images.githubusercontent.com/10763569/48389942-50012c00-e6c5-11e8-9239-85bc7fed4976.png">

<img width="862" alt="screen shot 2018-11-12 at 9 05 19 am" src="https://user-images.githubusercontent.com/10763569/48389951-58596700-e6c5-11e8-9c5a-b82fd84a538f.png">

**Comment by lemoustachiste** [comment]
@AnthonyRonning update:

- a .json url works, it's actually fetching. The error is with cert-verifier-js, which throws the following:
```Error: "Cannot verify this certificate without a transaction ID to compare against."``` cc @raiseandfall 
- there is indeed a problem that if we don't have a valid certificate definition, the auto-verify process still starts. I will fix this and open a PR

**Comment by lemoustachiste** [comment]
https://github.com/blockchain-certificates/blockcerts-verifier/pull/17

**Comment by AnthonyRonning** [comment]
Confirmed this is no longer an error, thanks @lemoustachiste !
