### ISSUE TITLE
ETH certificate not loading & verifying since bump to 1.19.0

### ISSUE THREAD

**Issue by raiseandfall** [blockchain-certificates/blockcerts-verifier#165]
The file to test is here: https://pbox.link/C02PD34MFVH8.json

The original ticket in the forum: 
https://community.blockcerts.org/t/blockcerts-org-verification-not-loading-json-anchored-in-ethereum/2071

**Comment by arunned** [comment]
I know why it is happening. it is doing a post event in /api/event/certificate at bus-events.js line 36. I do not have this API working. I think previously this was a non blocking error but now it is changed to blocking error.

**Comment by raiseandfall** [comment]
That's what I thought at first, but that feature hasn't changed in the last
version. It just logs an error. I think there's something wrong with the
actual changes to the BV itself.

**Comment by raiseandfall** [comment]
@arunned I just ran the BV locally on standalone (without the blockcerts.org host specific code), and your certificate is indeed not being loaded. I can also confirm that the issue is only happening when `display-mode="fullscreen"`, which was introduced in the last minor version.

**Comment by raiseandfall** [comment]
@arunned I found out the problem: your certificate json file is missing the `displayHtml` field [which is not required in the Blockcerts standard](https://cowcerts.readthedocs.io/en/develop/edu/specs/jsonld.html#assertion), however, the blockcerts-verifier needs it when the attribute `display-mode` is set to `"fullscreen"`. The blockcerts.org frontpage is using the `fullscreen` mode since today, which is why you had the issue for the first time today.

We need to think about a fallback solution when `display-mode` is set to `"fullscreen"`, but the loaded certificate does not have a `displayHtml` field.

@lemoustachiste what do you think ?

**Comment by arunned** [comment]
@raiseandfall Yes. you are right. I created another one with displayhtml and it is working. Thanks for quickly identifying the issue. I am glad that the certs we created without displayhtml are not for production. However once we issue production certs, they should always be working and have backward compatibility. 

Is there a sandbox for blockcerts.org web where we can test before the code moves to main site?

 It is making me nervous if the only way to make it work is to re-issue certificates. 

https://pbox.link/C02PD34MFVH9.json

Again, appreciate the fast response.

**Comment by raiseandfall** [comment]
@arunned We currently don't have a sandbox for blockcerts.org. For this specific issue you wouldn't have to re-issue the certificate, a fallback just needs to be added.
@lemoustachiste and I are currently busy on other matters, but we can look into it first half of next week. 
In the meantime, if you are interested to open a PR to address it, feel free to contribute.

Thank you again for reporting this issue!

**Comment by AnthonyRonning** [comment]
@arunned I agree that we should maintain backwards compat, but feel free to set up your own verifier if you're using it for production. We cannot guarantee the availability or reliability of blockcerts.org 100% of the time, so if you're doing mission critical stuff, set up your own production instance.

**Comment by arunned** [comment]
@AnthonyRonning Yes. agree. We do have one. Find the link below. It is always best to cross-verify with a 3rd party verifier. I think blockcerts is the only public verifier now. Not sure if there are any other independent verifier site... You can close this issue. 

https://pbox.link/verify/index.html?id=C02PD34MFVH9

**Comment by lemoustachiste** [comment]
@raiseandfall that sounds like a reasonable fallback, especially that `full` mode would also fail. In the meantime, this is not an error due to the latest release so we need to update blockcerts.org again.

**Comment by lemoustachiste** [comment]
Falling back to a v1 certificate in fullscreen mode: https://github.com/blockchain-certificates/blockcerts-verifier/pull/170

**Comment by lemoustachiste** [comment]
It is now corrected on blockcerts.org.
