### ISSUE TITLE
Verification on testnet indistinguable from mainnet

### ISSUE THREAD

**Issue by pompobit** [blockchain-certificates/blockcerts-verifier#18]
Hi,

I see that using a certificate json signed on testnet (Ropsten, for example) the result is the same like when using a certifcate signed on the mainnet.

I think that there should be some clear note on the verification prompt to warn the user that the certificate has been only signed on the test-net.

**Comment by lemoustachiste** [comment]
Hi there,

thanks for pointing this out.

The decision to render a different verification process is made from this line: https://github.com/blockchain-certificates/blockcerts-verifier/blob/master/src/selectors/certificate.js#L150. What we consider a test chain.

It should also be part of your certificate definition, under the name property:
https://github.com/blockchain-certificates/blockcerts-verifier/blob/master/src/selectors/certificate.js#L141

I don't mind modifying the `isTestChain` selector to encompass more test cases, but I am not personnally knowledgable on the various test chains out there. cc @AnthonyRonning

**Comment by lemoustachiste** [comment]
@pompobit would that work for you?

**Comment by pompobit** [comment]
I still didn't dig into the code to understand exactly how everything works so forgive me if I say stupid things but:
I can't find anywhere the code used to connect to the chain to retrieve the transaction specified in the certificate json. Can you point me it?
I'm asking that because instead that listing all the known testnet shouldn't be safer to check the network_id of the connected chain and if it is != 1 treat it as a non-mainnet chain?

**Comment by raiseandfall** [comment]
@pompobit This is actually done by our `cert-verifier-js` library: https://github.com/blockchain-certificates/cert-verifier-js

**Comment by AnthonyRonning** [comment]
I agree it's sub-optimal, and we actually have the option to run a bitcoin node inside of the same cert-issuer docker image and use that instead of API's. I think a PR that allows the choice sounds reasonable.

**Comment by lemoustachiste** [comment]
I think this has been resolved for a while now
