### ISSUE TITLE
Displaying additional context embedded in the certificate

### ISSUE THREAD

**Issue by jjalan** [blockchain-certificates/blockcerts-verifier#19]
Our certificate contains per recipient data.

1. How can this component be extended to include those extra data points?
2. How can the look and feel of the certificate be customized?

**Comment by AnthonyRonning** [comment]
The information you're looking for is all laid out here: https://github.com/blockchain-certificates/cert-tools

For the look of the certificate, you may use any HTML you want on a per recipient basis, using `displayHTML`.
