### ISSUE TITLE
compatibility with Next.js ecosystem

### ISSUE THREAD

**Issue by NailKhalimov** [blockchain-certificates/blockcerts-verifier#398]
Hi,

I have tried to use this package in Next.js ecosystem but met issue when importing module🤔

Can anyone help please?

![Снимок экрана 2020-04-07 в 16 04 33](https://user-images.githubusercontent.com/25770232/78673715-33cde280-78eb-11ea-8314-f088e695a6b8.png)

**Comment by lemoustachiste** [comment]
Hi @NailKhalimov,

I don't have a strong experience with NextJs, but what I am assuming is happening is that the package is made to be run in the browser, and not on the server. So server side rendering probably does not work, and this has not been developed with that use case in mind.

What I would suggest you try is preparing an HTML page that would reference the required packages (blockcerts-verifier as well as the webcomponents items as needed, see https://github.com/blockchain-certificates/blockcerts-verifier#production), with the `<blockcerts-verifier>` tag in it. I think this could work, but this is just a hunch. And I am not sure how this would impact the performance in your server side rendering. Please keep in mind this is not a React package.

**Comment by NailKhalimov** [comment]
Hi, @lemoustachiste 

Thanks for reply. I'm gonna think how solve this problem.👍
