### ISSUE TITLE
Verifiable Credentials update

### ISSUE THREAD

**Issue by crossoveranx** [blockchain-certificates/blockcerts-verifier#568]
I wanted to utilize this library for verifying verifiable credentials. Has this been implementing already? I created a couple certificates using the alpha versions in cert-tools and cert-issuer, but I receive the message that it's not a valid credential.

**Comment by raiseandfall** [comment]
Hi @crossoveranx 
I believe @lemoustachiste worked on implementing verification of VCs, but he would have to confirm his status on it. 
However I'm aware of another issue (#577) that might be related to yours (Blockcerts v3 is an implementation of VCs).

**Comment by lemoustachiste** [comment]
Hi @crossoveranx, sorry I just got back from holidays. 
This verifier is only a UI wrapper around our other verifier project, https://github.com/blockchain-certificates/cert-verifier-js. We are currently in the process of assessing the extent of its compatibility with VC (via this tool: https://github.com/w3c/vc-test-suite/), but I can already assure you that at this point in time it will not verify a VC that's not blockcerts, or only partially, and that you shouldn't trust it to do this job. It is possible that in the future we ensure cross-compatibility with other VCs implementations, but you shouldn't expect that too soon.

To verify a Verifiable Credential or Presentation, you should have a look at vc.js (https://github.com/digitalbazaar/vc-js).
