### ISSUE TITLE
Valid V3-alpha Blockcerts show as invalid on mobile browsers on first load only

### ISSUE THREAD

**Issue by amazanzan** [blockchain-certificates/blockcerts-verifier#577]
### Environment: 
I have confirmed this bug using Chrome and Safari on iOS on blockcerts.org as well as my own deployment (blockcerts-verifier@1.33.2)

### Method to reproduce: 
Just load a valid V3-alpha Ethereum Blockcert by URL on iOS Chrome or Safari. (another mobile browser may work too. Not sure whether this bug occurs with Bitcoin Blockcerts.)
The certificate will not validate, displaying `Invalid Merkle Receipt. Proof hash did not match Merkle root`
However, if you clear the credential with the "X" icon and enter the same URL again, it will show as valid.

### Proposal:
I'm not sure of the cause, but since blockcerts-verifier is clearly capable of validating the credential properly even on mobile, I would guess there's just a quick fix to be made in the verification sequence for V3 credentials on mobile.

Thoughts?

**Comment by raiseandfall** [comment]
Hi @amazanzan 
Thanks for reporting the issue. Before we dig any further, have you tried to test with the latest build version ([1.33.4](https://github.com/blockchain-certificates/blockcerts-verifier/releases/tag/v1.33.4)) ?

**Comment by amazanzan** [comment]
Thanks for responding @raiseandfall, I'll check it with the latest version as soon as I get the opportunity and get back to you.

**Comment by amazanzan** [comment]
Hi @raiseandfall, I was able to confirm that the error still occurs on 1.33.4

**Comment by raiseandfall** [comment]
Hi @amazanzan, thank you for confirming. I have a pretty busy schedule but I'm gonna try to investigate this week. Feel free to add more info here or contribute if you can as well, it's always greatly appreciated!

**Comment by lemoustachiste** [comment]
I am going to take a look at this today.

**Comment by lemoustachiste** [comment]
Could replicate the bug. That's going to be interesting...

**Comment by lemoustachiste** [comment]
so what I found is that, for some reason, when we parse the local merkleRoot, on first load, iOS prepends an extra space to the hash string, which modifies the value of the re-hashed output, which then fails.
Why doesn't it do it with a v2 certificate? 🤷 
Why on first load? 🤷 
Trimming does the trick...

**Comment by lemoustachiste** [comment]
@amazanzan on susbsequent load does your certificate verify as expected?

**Comment by lemoustachiste** [comment]
@amazanzan could you confirm that v1.33.6 solves your issue?
I am closing this as on my side it looks acceptable.

**Comment by amazanzan** [comment]
@lemoustachiste Thanks for your work on this bug! Your fixes seem very promising but I have to report that I'm still experiencing this bug on all browsers on iOS...
I've double and triple checked (used private browsing and cleared my entire cache on Chrome mobile) but no dice.
The certificate I'm checking with works fine on desktop browsers.

Is there a domain with v1.33.6 deployed where you are certain a V3-alpha Ethereum credential will validate on iOS browsers?
I'd be happy to check once more to see if the problem is somehow on my end.

**Comment by amazanzan** [comment]
Actually @lemoustachiste let me check my deployment again—I'll let you know for sure in a bit here.

**Comment by amazanzan** [comment]
@lemoustachiste Still getting the bug. The issue seems to be unresolved although I hope I'm wrong.
