### ISSUE TITLE
Correct method for debugging

### ISSUE THREAD

**Issue by flachica** [blockchain-certificates/blockcerts-verifier#646]
I have some failures when verifying the certificates that I issue. I think the problems stem from misconfiguration in cert-issuer. But to help me find the problem I would like to be able to debug this component. Could you help me debug this project? What tools do you use and what configuration files? Thank you

**Comment by lemoustachiste** [comment]
Hi @flachica sorry I didn't see this issue before.
I am not sure how to help. If you really want to debug the verification, you'd need to run [`cert-verifier-js`](https://github.com/blockchain-certificates/cert-verifier-js) either on a page or with node. Then you can edit the code to add some console logs or anything that helps.

This specific project is just a UI wrapper around the aforementioned one.

**Comment by flachica** [comment]
Thanks @lemoustachiste. I do that and run correctly
