### ISSUE TITLE
Unable to run locally [ need help ]

### ISSUE THREAD

**Issue by mohitrakhade20** [blockchain-certificates/blockcerts-verifier#669]
> $ npm run start

( its showing this error )

```
Error: Failed to replace env in config: ${NPM_TOKEN}
    at /usr/share/npm/lib/config/core.js:415:13
    at String.replace (<anonymous>)
    at envReplace (/usr/share/npm/lib/config/core.js:411:12)
    at parseField (/usr/share/npm/lib/config/core.js:389:7)
    at /usr/share/npm/lib/config/core.js:330:24
    at Array.forEach (<anonymous>)
    at Conf.add (/usr/share/npm/lib/config/core.js:328:23)
    at ConfigChain.addString (/usr/share/nodejs/config-chain/index.js:244:8)
    at Conf.<anonymous> (/usr/share/npm/lib/config/core.js:316:10)
    at /usr/share/nodejs/graceful-fs/graceful-fs.js:115:16
/usr/share/npm/lib/npm.js:59
      throw new Error('npm.load() required')
      ^

Error: npm.load() required
    at Object.get (/usr/share/npm/lib/npm.js:59:13)
    at process.errorHandler (/usr/share/npm/lib/utils/error-handler.js:205:32)
    at process.emit (events.js:198:13)
    at process._fatalException (internal/bootstrap/node.js:497:27)
```

**Comment by lemoustachiste** [comment]
Hi, 

this is not an issue directly with this component but rather with NPM. However the fix is easy, you need to modify your .bashrc and add this line:

`export NPM_TOKEN=[an-npm-token-generated-from-npm.com]`, source your new .bashrc (or restart your terminal) and you shouldn't have an issue.

I do think you don't necessarily need to have a specific token, so you could potentially put any string instead of generating a token from npm.com. But if that does not work you will need to do it.

Hope this helps

**Comment by mohitrakhade20** [comment]
Sure, I will follow this. Thank you so much. Can you tell me if I got stuck where should I contact you or other contributors?

**Comment by lemoustachiste** [comment]
using this repo for issues is good. You can tag me if you want, but I will see the issue being opened

**Comment by mohitrakhade20** [comment]
Thank you @lemoustachiste

**Comment by mohitrakhade20** [comment]
Its still not running, I tried running it the way you said @lemoustachiste 
![Uploading Screenshot from 2020-10-10 17-16-17.png…]()

**Comment by mohitrakhade20** [comment]
Its still not running, I tried running it the way you said @lemoustachiste 
![Screenshot from 2020-10-10 17-16-17](https://user-images.githubusercontent.com/48031017/95654251-7da6b800-0b1c-11eb-892b-8c132aafd4e4.png)

**Comment by mohitrakhade20** [comment]
Its still not running, I tried running it the way you said @lemoustachiste 
![Screenshot from 2020-10-10 17-16-17](https://user-images.githubusercontent.com/48031017/95654251-7da6b800-0b1c-11eb-892b-8c132aafd4e4.png)

**Comment by mohitrakhade20** [comment]
To solve NPM_TOKEN err : 
In npmrc file
Line of Code: //registry.npmjs.org/:_authToken=${NPM_TOKEN} (Remove this code)

then install concurrently 

  ` npm install concurrently`
  ` npm run start`

This worked for me

**Comment by lemoustachiste** [comment]
Just for the record this is not the proper fix for this issue.

**Comment by lemoustachiste** [comment]
The NPM_TOKEN is required in CI to publish the new package, hence why it is here. Correct fix is by setting this variable in your environment.

**Comment by mohitrakhade20** [comment]
I will try again by creating npm token although I tried it and it didn't work for me. Now I will try token generation with cli.

**Comment by lemoustachiste** [comment]
I think if you don't intend to make PRs you are fine with what you did.
