### ISSUE TITLE
Issue in running locally

### ISSUE THREAD

**Issue by jainil-4801** [blockchain-certificates/blockcerts-verifier#670]
>npm run start

It's showing the error of "The system cannot find the file :mock-server". 

```
HP@LAPTOP-K2A8KOQA MINGW64 ~/Desktop/blockcerts-verifier (master)
$ npm run start

> @blockcerts/blockcerts-verifier@0.0.0-dev start C:\Users\HP\Desktop\blockcerts-verifier
> concurrently 'rollup -c rollup.dev.config.js -w' 'npm run styles:compile:watch' 'npm run start:mock-server'

[2] The filename, directory name, or volume label syntax is incorrect.
[0] ''rollup' is not recognized as an internal or external command,
[0] operable program or batch file.
[2] styles:compile:watch' exited with code 1
[0] 'rollup exited with code 1
[1] 'run' is not recognized as an internal or external command,
[1] operable program or batch file.
[3] ''npm' is not recognized as an internal or external command,
[3] operable program or batch file.
[4] 'run' is not recognized as an internal or external command,
[4] operable program or batch file.
[1] run exited with code 1
[4] run exited with code 1
[3] 'npm exited with code 1
[5] The system cannot find the file :mock-server'.
[5] start:mock-server' exited with code 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @blockcerts/blockcerts-verifier@0.0.0-dev start: `concurrently 'rollup -c rollup.dev.config.js -w' 'npm run styles:compile:watch' 'npm run start:mock-server'`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @blockcerts/blockcerts-verifier@0.0.0-dev start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\HP\AppData\Roaming\npm-cache\_logs\2020-10-09T10_26_07_222Z-debug.log

```

So, please can anyone help how should I remove this error.

Steps I have followed:- 
1. Clone the repository
2. Install the dependencies through 
>npm install
3. npm run start

**Comment by lemoustachiste** [comment]
it looks like an issue with Windows:
```
The system cannot find the file :mock-server'.
[5] start:mock-server' exited with code 1
```
As if somehow it was interpreting this npm instruction as a file name. 

I am not familiar with npm on Windows as I have never ran it here. So I'd suggest you research the issue online.
But I think a quick workaround - although not a long term solution - could be to rename the package.json scripts to remove the `:` and maybe use `-` or whatever.

**Comment by jainil-4801** [comment]
@lemoustachiste Thanks for your reply. 

As an alternative to concurrently, I have used npm-run-all with breaking single start script into 3 scripts, now it doesn't give me an error but when I [click](http://localhost:8081/demo/),  


```
404 Not Found

C:\Users\HP\Desktop\blockcerts-verifier\test\fixtures\demo\index.html

(rollup-plugin-serve)
```
As far as I understand it couldn't run all three scripts


Changed Scripts commands
```
"one": "rollup -c rollup.dev.config.js -w",
"two": "npm run styles:compile:watch",
"three": "npm run start:mock-server"
```

With running the following command on bash 

>npm-run-all one two three

**Comment by lemoustachiste** [comment]
I'm sorry this really looks like issues with Windows and I really cannot help there. 

`rollup-plugin-serve` instruction is defined here: https://github.com/blockchain-certificates/blockcerts-verifier/blob/master/rollup.dev.config.js#L24 (executed by your instruction `one`). What it does is take these different folders and put them all together for availability on the server. You should try and see if there is an issue with windows and rollup, maybe things are somewhat different.

Other thing I can think of if you don't want to spend your day debugging is installing a Linux VM on your machine, and from there you should be able to work with this package. 

Really sorry for the inconvenience

**Comment by mohitrakhade20** [comment]
![Screenshot from 2020-10-10 17-08-41](https://user-images.githubusercontent.com/48031017/95654165-ba25e400-0b1b-11eb-9f91-4688c5e55205.png)

can you help me with this

**Comment by lemoustachiste** [comment]
You're second issue is similar to this one: https://github.com/blockchain-certificates/blockcerts-verifier/issues/669.

Your first issue looks like you haven't installed dependencies. Did you run `npm install`?

**Comment by lemoustachiste** [comment]
but honestly you shouldn't be running the styles compile on your own unless you absolutely know what you are doing
